### ISSUE TITLE
Caller reporting is off by one by default for me

### ISSUE THREAD

**Issue by binaryphile** [bombsimon/logrusr#19]
Thanks for logrusr btw.

The problem I'm having is that the default setup for logr/logrusr is a call depth of 1.  This means that by default, I don't get the correct caller location.

Modifying the logger before use with WithCallDepth(0) fixes it, but the default behavior should act as expected and this does not.

I tracked it to the Init method which applies the logr.RuntimeInfo.  logr calls this with depth 1, always.  There's no way to stipulate a sensible default, but since I'm figuring that that's what works correctly for other backends, I'm guessing that any necessary change would originate in this project rather than logr.  I could be wrong there, of course.  I haven't looked at how other backends interpret that.

What do you think?

**Comment by bombsimon** [comment]
Thanks for the report!

I need to look into this but I do agree the default behaviour should be correct. There are test for this feature and it seems like the one that does not set any custom call depth produces the expected behaviour. 

https://github.com/bombsimon/logrusr/blob/6409c428bc015455c9041dda947febf1290e8bac/logrusr_test.go#L247-L271

Do you have a minimum reproducible example for this to show me?

**Comment by binaryphile** [comment]
Hm.  This set of tests doesn't test logrusr.  The "log" in the logFunc arguments is a logrus instance, so none of these tests exercise your code.

In particular, the code at issue is here:

https://github.com/bombsimon/logrusr/blob/main/logrusr.go#L78

logr always passes in the following to Init:

https://github.com/go-logr/logr/blob/master/logr.go#L411

So depth always gets set to 1 on the logrus instance.  Your tests show it as 0, since the logrus instance wasn't instantiated by logr.

**Comment by binaryphile** [comment]
I deleted the last comment I made because I misread the code and said something silly. :)

The problem here is that the test is insufficient.  If you debug the test, you can see that the output log cites line 300 as the caller.  However, the caller is actually line 250.  When I debug the test and set depth to 0 manually before the log is output, I get the correct attribution.

Unfortunately, while citing the actual line number in the assertion regex is fragile, it's the only way I can see to distinguish the correct behavior.

Logr uses the following value in runtimeInfo to call your sink's Init:

https://github.com/go-logr/logr/blob/master/logr.go#L411

It gets set when you copy it here:

https://github.com/bombsimon/logrusr/blob/main/logrusr.go#L78

I think the correct answer is to fix the test, then fix the code by subtracting one from the call depth argument before setting the depth field.

Presuming that's correct, one alternative would be to look at how other backends to see how they deal with it.  Another would be to get logr to pass in the zero value or allow the user to override.

**Comment by bombsimon** [comment]
Thanks for the info! I'll try to look into this during the weekend if you don't plan to file a PR

**Comment by bombsimon** [comment]
I think the original miss here, and I'm not sure if this has changed, is that `logr` defaults call depth to 1, not 0: https://github.com/go-logr/logr/blob/a49c9717d660988d99b6f931e67c49745caacbcd/logr.go#L342-L343.

Anyway, I fixed this in #21 and will draft a new release soon. Thanks for the report and help!
