### ISSUE TITLE
Doesn't appear to support the logr.Marshaler interface.

### ISSUE THREAD

**Issue by derekbassett** [bombsimon/logrusr#26]
Looking at this implementation it does not appear to support the logr.Marshaller interface.

I will put together a PR to see if I can implement this interface.

**Comment by bombsimon** [comment]
Thanks for the issue! Please feel free to give it a go and let me know if you won't make it and I can probably put something together!

Short term for anyone missing this, it's possible to implement this yourself by using a custom format func that will be called with ever non built-in value, example here: https://github.com/bombsimon/logrusr/blob/d198d3e84a78c6115fb1e18c1ccb66193530e9c7/example/main.go#L68-L74
