### ISSUE TITLE
WithCallDepth should be additive

### ISSUE THREAD

**Issue by muhlemmer** [bombsimon/logrusr#27]
The logr documentation on [`WithCallDepth`](https://pkg.go.dev/github.com/go-logr/logr#Logger.WithCallDepth) and [`CallDepthLogSink`](https://pkg.go.dev/github.com/go-logr/logr#CallDepthLogSink) interface both say:

> Successive calls to this are additive.

However, this implementation replaces the current `depth` instead of adding:

https://github.com/bombsimon/logrusr/blob/d198d3e84a78c6115fb1e18c1ccb66193530e9c7/logrusr.go#L213-L220

**Comment by bombsimon** [comment]
Thanks for the issue! I added a fix but might take a couple of days before drafting a new release. Saw some other changes I'm not yet up to date with that I might want to squeeze in. Hope it's not blocking you!

**Comment by bombsimon** [comment]
Sorry for the delay, I have now published [v4.1.0](https://github.com/bombsimon/logrusr/releases/tag/v4.1.0).
