### ISSUE TITLE
logr v1.0.0-rc1 includes breaking changes

### ISSUE THREAD

**Issue by thockin** [bombsimon/logrusr#4]
logr made BREAKING CHANGES for implementations to prep for 1.0.0

Here's the glogr PR that adopts the new logr API changes: go-logr/glogr#13 - this includes a bunch of perf-related changes too (sorry).

The changes are not THAT complicated. Please feel free to shout if they don't make sense.

**Comment by thockin** [comment]
https://github.com/go-logr/zapr/pull/28 is another example

**Comment by bombsimon** [comment]
Cool, thanks for the heads up! Will look at implementing the changes asap! Of course, PRs are welcome. 😸

**Comment by bombsimon** [comment]
@thockin Would you mind giving #5 a quck look (at least the [commit to adapt v1.0.0-rc1](https://github.com/bombsimon/logrusr/pull/5/commits/ac3ce3c3bac75ca0cb2f6b5a49cf2e45e0d07edd) to see if it looks OK and compatible with logr 1.0.0?
